// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnyvplrnnvwbyxnpjddb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueXZwbHJubnZ3Ynl4bnBqZGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjE3MTMsImV4cCI6MjA2Mjk5NzcxM30.xWPPChLnJWNMPNyns3Ejs9n5j1XV6ephVeE8A6ej2dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);